steps:
  # API pipeline
  - name: "gcr.io/cloud-builders/docker"
    id: "build-api"
    waitFor: ["-"]
    dir: "api"
    args:
      - "build"
      - "-t"
      - "us-central1-docker.pkg.dev/$PROJECT_ID/tora/api:$COMMIT_SHA"
      - "."
  - name: "gcr.io/cloud-builders/docker"
    id: "push-api"
    waitFor: ["build-api"]
    args:
      - "push"
      - "us-central1-docker.pkg.dev/$PROJECT_ID/tora/api:$COMMIT_SHA"
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    id: "deploy-api"
    waitFor: ["push-api"]
    dir: "api"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        gcloud run deploy tora-api \
          --image us-central1-docker.pkg.dev/$PROJECT_ID/tora/api:$COMMIT_SHA \
          --region us-central1 \
          --platform managed \
          --allow-unauthenticated \
          --cpu 1.0 \
          --memory 512Mi \
          --min-instances 0 \
          --max-instances 5 \
          --set-secrets DATABASE_URL=DATABASE_URL:latest,SUPABASE_URL=SUPABASE_URL:latest,SUPABASE_API_KEY=SUPABASE_KEY:latest,PRIVATE_ANTHROPIC_KEY=ANTHROPIC_KEY:latest,SUPABASE_JWT_SECRET=SUPABASE_JWT_SECRET:latest \
          --set-env-vars FRONTEND_URL=https://tora-web-1030250455947.us-central1.run.app

  # Web pipeline
  - name: "gcr.io/cloud-builders/docker"
    id: "build-web"
    waitFor: ["-"]
    dir: "web"
    args:
      - "build"
      - "-t"
      - "us-central1-docker.pkg.dev/$PROJECT_ID/tora/web:$COMMIT_SHA"
      - "."
  - name: "gcr.io/cloud-builders/docker"
    id: "push-web"
    waitFor: ["build-web"]
    args:
      - "push"
      - "us-central1-docker.pkg.dev/$PROJECT_ID/tora/web:$COMMIT_SHA"
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    id: "deploy-web"
    waitFor: ["push-web"]
    dir: "web"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        gcloud run deploy tora-web \
          --image us-central1-docker.pkg.dev/$PROJECT_ID/tora/web:$COMMIT_SHA \
          --region us-central1 \
          --platform managed \
          --allow-unauthenticated \
          --cpu 1.0 \
          --memory 512Mi \
          --min-instances 0 \
          --max-instances 5 \
          --set-env-vars PUBLIC_API_BASE_URL=https://tora-api-1030250455947.us-central1.run.app \
          --port 3000

  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    waitFor: ["deploy-api", "deploy-web"]
    entrypoint: "bash"
    args:
      - "-c"
      - |
        # Clean up API images (keep 3 most recent)
        gcloud artifacts docker images list us-central1-docker.pkg.dev/$PROJECT_ID/tora/api \
          --sort-by=~CREATE_TIME --limit=999 --format="value(IMAGE)" | \
          tail -n +3 | xargs -r gcloud artifacts docker images delete --quiet || true

        # Clean up web images (keep 3 most recent)
        gcloud artifacts docker images list us-central1-docker.pkg.dev/$PROJECT_ID/tora/web \
          --sort-by=~CREATE_TIME --limit=999 --format="value(IMAGE)" | \
          tail -n +3 | xargs -r gcloud artifacts docker images delete --quiet || true

timeout: "1600s"
options:
  machineType: "E2_MEDIUM"
