steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      - build
      - -t
      - "us-central1-docker.pkg.dev/$PROJECT_ID/tora/rust:$COMMIT_SHA"
      - .
  - name: "gcr.io/cloud-builders/docker"
    args:
      - push
      - "us-central1-docker.pkg.dev/$PROJECT_ID/tora/rust:$COMMIT_SHA"

  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    dir: "api"
    entrypoint: bash
    args:
      - -c
      - |
        gcloud run deploy tora-rust \
          --image us-central1-docker.pkg.dev/$PROJECT_ID/tora/rust:$COMMIT_SHA \
          --region us-central1 \
          --platform managed \
          --allow-unauthenticated \
          --cpu 1.0 \
          --memory 512Mi \
          --min-instances 0 \
          --max-instances 5 \
          --set-secrets SUPABASE_PASSWORD=SUPABASE_PASSWORD:latest
options:
  machineType: "E2_MEDIUM"
timeout: "1600s"
