steps:
  - name: "gcr.io/cloud-builders/docker"
    dir: "web"
    args:
      - build
      - -t
      - "us-central1-docker.pkg.dev/$PROJECT_ID/tora/app:$COMMIT_SHA"
      - .
  - name: "gcr.io/cloud-builders/docker"
    args:
      - push
      - "us-central1-docker.pkg.dev/$PROJECT_ID/tora/app:$COMMIT_SHA"

  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    dir: "web"
    entrypoint: bash
    args:
      - -c
      - |
        gcloud run deploy tora \
          --image us-central1-docker.pkg.dev/$PROJECT_ID/tora/app:$COMMIT_SHA \
          --region us-central1 \
          --platform managed \
          --allow-unauthenticated \
          --cpu 1.0 \
          --memory 512Mi \
          --min-instances 0 \
          --max-instances 10 \
          --set-secrets PUBLIC_SUPABASE_URL=SUPABASE_URL:latest,PUBLIC_SUPABASE_ANON_KEY=SUPABASE_KEY:latest,PRIVATE_ANTHROPIC_KEY=ANTHROPIC_KEY:latest,PRIVATE_SERVICE_ROLE_KEY=SUPABASE_SERVICE_KEY:latest
options:
  machineType: "E2_MEDIUM"
timeout: "1600s"
