steps:
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    dir: "web"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        # Create .env file
        echo "Creating .env file from Secret Manager secrets"
        echo "PUBLIC_SUPABASE_URL=$(gcloud secrets versions access latest --secret=SUPABASE_URL)" >> .env
        echo "PUBLIC_SUPABASE_ANON_KEY=$(gcloud secrets versions access latest --secret=SUPABASE_KEY)" >> .env
        echo "PRIVATE_ANTHROPIC_KEY=$(gcloud secrets versions access latest --secret=ANTHROPIC_KEY)" >> .env
        echo "PRIVATE_SERVICE_ROLE_KEY=$(gcloud secrets versions access latest --secret=SUPABASE_SERVICE_KEY)" >> .env
        echo ".env file created successfully"

  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    dir: "web"
    entrypoint: "bash"
    args:
      [
        "-c",
        "gcloud config set app/cloud_build_timeout 1600 && gcloud app deploy",
      ]
timeout: "1600s"
