steps:
  - name: 'gcr.io/cloud-builders/docker'
    dir: 'web'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/happyplace', '.']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    dir: 'web'
    entrypoint: bash
    args:
      - -c
      - |
        gcloud run deploy happyplace \
          --image gcr.io/$PROJECT_ID/happyplace \
          --region us-central1 \
          --platform managed \
          --allow-unauthenticated \
          --set-secrets PUBLIC_SUPABASE_URL=SUPABASE_URL:latest,PUBLIC_SUPABASE_ANON_KEY=SUPABASE_KEY:latest,PRIVATE_ANTHROPIC_KEY=ANTHROPIC_KEY:latest,PRIVATE_SERVICE_ROLE_KEY=SUPABASE_SERVICE_KEY:latest
timeout: '1600s'
